### ISSUE TITLE
Delete token button

### ISSUE THREAD

**Issue by jdbann** [tableparty/table#104]
Tokens are currently removed from the map by dragging them back to the map drawer. Dragging can be useful for targeting a specific destination when dragging a token on to the map. When the intention is to remove the token, the final destination doesn't matter, so dragging to the drawer is a frustrating requirement.

```
When a token is no longer needed
I want to quickly delete or remove the token without moving my focus away from the map
So that I can focus on the next action in combat
```

**Comment by cpytel** [comment]
What do you think about bringing up a menu when you click (or double click?) on a token on the map? I'm thinking of a circular menu of some kind around the token, like this: https://codepen.io/lbebber/pen/RNgBPP

**Comment by jdbann** [comment]
Yeah, I was expecting something like this. In my head there was a set of controls that appeared in the bottom right as a load of floating buttons. Clicking on a token would effectively select it, then the buttons would appear. I think that's nicer for preventing the buttons getting in the way of the map, but it's a pain for people on computers. To help with that I think the buttons would all be mapped to [hotkeys](https://github.com/github/hotkey).

The specific example reminds me a bit of what Roll 20 does, whether that's a good thing or not I don't know. It's a lot easier for mouse-users.

**Comment by cpytel** [comment]
I've got this underway in a branch. Here is a sneak peek: deleting and stashing tokens, entirely controlled by the keyboard in this video. Unfortunately, the video doesn't show any other keys in the overlap except the error and enter keys.

![ScreenFlow](https://user-images.githubusercontent.com/5015/91650982-c3b82880-ea54-11ea-924e-27098b32794a.gif)

**Comment by jdbann** [comment]
Ooh yeah this looks great! Is that tab selection as well?

**Comment by cpytel** [comment]
Yeah, It turns out that using tab will conflict with built-in tab focusable browser elements, and since this is _selection_ not focus, it made sense to use a different key. So you right or left arrow to move which token is selected, or hold shift and press the right or left arrow to select multiple tokens.

You can also use the mouse for selecting individual tokens, or hold shift to select multiple.
