### ISSUE TITLE
Showing removed tokens in the drawer is impractical in large maps

### ISSUE THREAD

**Issue by jdbann** [tableparty/table#105]
The token drawer quickly gets filled with killed monsters. At that point it becomes harder to find what you're after.

```
When an encounter starts
I want to quickly find the right tokens in the drawer
So that I can keep my mind on the encounter
```

```
When a monster reappears
I want to quickly re-add the original token
So that I can keep my mind on the encounter
```

**Comment by jdbann** [comment]
Trying to be careful not to prescribe a solution here. We discussed stacking the tokens previously, that could work here.

Alternatively, we could make the identifiers editable. I could drop a new instance of the token on the map and rename it to the original instance.

Or we could split the token drawer up to have a 'graveyard', which might be useful information for a DM who wants to calculate XP?

**Comment by jdbann** [comment]
#70 is an additional impact of a large map with lots of discarded tokens

**Comment by cpytel** [comment]
Regardless of what we do to fully solve this problem, I totally think it makes sense to be able to edit the identifier of any token. I'm thinking you bring up the token's menu (mentioned in #104) and then can click to edit the token. From there, you could change the identifier. I'm also envisioning that you could change the image for that individual token from there as well.

**Comment by jdbann** [comment]
Shall we spin off editable identifiers into a new ticket? In my head I had the identifiers as something you could edit-in-place (I'm sure there's a proper term for this?) rather than needing extra controls. But then a token menu will definitely come in handy for plenty of other things like showing/hiding the name.

**Comment by jdbann** [comment]
Now that we have a delete function for tokens, I'm going to close this
