### ISSUE TITLE
What else is required for 'Playable'?

### ISSUE THREAD

**Issue by jdbann** [tableparty/table#42]
We have a [Playable milestone](https://github.com/jdbann/table/milestone/1) and aside from creating tokens from templates and the token drawer it's pretty empty.

Is there anything extra you think it would need @cpytel?

**Comment by cpytel** [comment]
No, I think that’s it!

**Comment by cpytel** [comment]
The one thing that comes to mind as a feature that we don’t have an issue for but that we might want to eventually have because it’s not included in any of the other tools we’re using is tracking initiative order, but I don’t think that needs to be in the playable milestone.

**Comment by cpytel** [comment]
I just remembered something we may find we need.

One thing that is heavily by groups I’ve played with in Roll 20 is a way to “point to” something on the map. We’ve actually been doing this automatically in Figma because you can see everyone mouse pointers.

In Roll 20 you click once on the map and it fleshed a circle that grows out leads from where you clicked.

We might not _need_ this in order to play, but I suspect that if we don’t have it we will find that we want it.

**Comment by jdbann** [comment]
> One thing that is heavily by groups I’ve played with in Roll 20 is a way to “point to” something on the map.

Yeah that's a good idea. I've created #45

> The one thing that comes to mind as a feature that we don’t have an issue for but that we might want to eventually have because it’s not included in any of the other tools we’re using is tracking initiative order, but I don’t think that needs to be in the playable milestone.

For some context, I was tracking initiative using D&D Beyond's encounter builder. It's helpful for the monster stats and also tracking health, but the order isn't shared with the party.

<img width="1486" alt="Screenshot 2020-04-14 at 07 36 14" src="https://user-images.githubusercontent.com/1191840/79193485-a296c880-7e22-11ea-9fe4-f11f2639c103.png">

Avrae (the Discord bot) also has an [initiative system](https://avrae.readthedocs.io/en/latest/cheatsheets/dm_combat.html#starting-combat) but it seems like quite a commitment to learn their whole set of obtuse commands.

**Comment by cpytel** [comment]
@jdbann how did the first session go? From a DM perspective were there any rough edges or issues?

How was token creation and usage? Should we consider simplifying to something like I had outlined [here](https://github.com/jdbann/table/pull/48#issuecomment-623152031).

**Comment by jdbann** [comment]
It was very exciting to use Table! I think it definitely worked well for us. I'll throw out the things I noticed:

- Token visibility was tricky - couldn't hide a token without taking it off the map and couldn't place tokens without revealing them

- Couldn't delete tokens for dead creatures

- Made the mistake again of having numbered creatures when D&D encounter tracker uses letters

- I got nervous about zooming and panning the map because I was using an odd screen size. I was using a tall and narrow window so I could have notes alongside the map - but the middle of the map was mostly empty and I feared that users would mostly see the empty middle space
<img width="1280" alt="Screenshot 2020-05-09 at 13 56 08" src="https://user-images.githubusercontent.com/1191840/81474374-ec45b980-91fc-11ea-88ac-cac5a849aff9.png">

- The `Player`/`Creature` options meant that I couldn't have a generic (un-numbered) token for Big Al without him appearing in the drawer for all maps - creating a generic token would still be helpful

**Comment by jdbann** [comment]
> How was token creation and usage? Should we consider simplifying to something like I had outlined here.

I didn't have to do a lot of token management during the session, just dragging them on to the map. I have some reservations about that approach but I'm not sure where would be best to discuss them.

**Comment by jdbann** [comment]
I’ll try put together a pitch for how I would see a token refactor working á la Shape Up

**Comment by cpytel** [comment]
> Token visibility was tricky - couldn't hide a token without taking it off the map and couldn't place tokens without revealing them

> Couldn't delete tokens for dead creatures

My thinking was we were trying to keep things simple by relying exclusively on the token drawer for visibility. If it's on the map, it's visible. If it's in the drawer, it's not. So, for a dead creature, you'd move it back to the drawer. For placing creatures, you move them to the places you want from the drawer.

It sounds like that is cumbersome, especially for the size battle we're having now, having to place all the tokens on the fly.

Does the possibility of fog help with the issue of token placement? Allowing you to place a bunch of tokens that aren't actually visible to players until they are revealed when the fog is removed?

Secondarily, do we want dead creatures to no longer be visible, or would it better to mark them in some way?

> Made the mistake again of having numbered creatures when D&D encounter tracker uses letters

Should we change from numbers to incrementing letters?

**Comment by jdbann** [comment]
The issue with dead orcs was mostly that my drawer started to fill with Orc 1, Orc 2, Orc 4, Orc 7 etc and I had no need to use them again. Plus dragging them all the way back to the drawer was an unnecessary step. Detail is required to put them in the right location, but I don't want to think about where to put them when they're redundant.

Fog might help, but I don't really decide where things are until they're needed. You might have approached the shrine during the day, or created a distraction. It's more efficient to deploy things as they're needed.

I think it would be helpful to be able to drag a copy of a creature off any existing creature token. Means I don't need to go all the way back to the drawer.

As far as handling dead creatures, I don't really do much with the bodies. I try to avoid getting into 'looting the bodies' and that kind of thing. Do you have any suggestions on reasons to keep them around?

> Should we change from numbers to incrementing letters?

It might be easier for the particular tool I use. My ideal situation though would be giving them identifying features. I'd rather invite players to say they swing their axe at the orc with the broken nose, or the nervous looking one in the corner.

**Comment by cpytel** [comment]
> The issue with dead orcs was mostly that my drawer started to fill with Orc 1, Orc 2, Orc 4, Orc 7 etc and I had no need to use them again. Plus dragging them all the way back to the drawer was an unnecessary step. Detail is required to put them in the right location, but I don't want to think about where to put them when they're redundant.

I've been thinking about the idea of turning the new token button into a trash icon when you start to drag a token. To delete a token, you could drop it onto the trash. It might be handy to have shortcuts though, like the ability to right-click on a token and choose delete.

> I think it would be helpful to be able to drag a copy of a creature off any existing creature token. Means I don't need to go all the way back to the drawer.

This aligns with my idea of making it so that you can duplicate any token either by holding the option key while dragging (like macOS files) or some other way.

> As far as handling dead creatures, I don't really do much with the bodies. I try to avoid getting into 'looting the bodies' and that kind of thing. Do you have any suggestions on reasons to keep them around?

Not really.

> It might be easier for the particular tool I use. My ideal situation though would be giving them identifying features. I'd rather invite players to say they swing their axe at the orc with the broken nose, or the nervous looking one in the corner.

I think the ideal way to foster that is to get away from the map and start giving more verbal descriptions, but it would be nice if Table can help foster it.

**Comment by jdbann** [comment]
> It might be handy to have shortcuts though, like the ability to right-click on a token and choose delete.

Yeah, I'd rather have a way to quickly remove tokens from the map than manage what's in the drawer. Maybe in the drawer the similar tokens can be grouped together or stacked?

> This aligns with my idea of making it so that you can duplicate any token either by holding the option key while dragging (like macOS files) or some other way.

Absolutely yes, that's how I was imagining it too.

> I think the ideal way to foster that is to get away from the map and start giving more verbal descriptions, but it would be nice if Table can help foster it.

Yeah I think on a fight with 10s of orcs and a few ogres we can't really handle the luxury of characterisation. This is maybe a secondary aim of the tool - to provide an additional layer of detail or imagination to the encounters.

**Comment by cpytel** [comment]
I like the ides of stacking similar tokens.

When I was originally doing creatures, I thought about actually just deleting copies when you move them back to the drawer automatically, essentially making it so there is only one creature in the drawer and copies on the map. While I think this would work in most cases, I didn't strike me as what people would _expect_ to happen using it the first time, and I figured that might be too disruptive for the case where you want to get a creature off the map, or if you want to queue up a bunch of tokens in advance that you'll use in your session.

Grouping/stacking might be a good compromise.

**Comment by cpytel** [comment]
What do you think about closing this issue?

**Comment by jdbann** [comment]
Yeah, I think we can count it as 'playable' now
