### ISSUE TITLE
Invite other DMs?

### ISSUE THREAD

**Issue by jdbann** [tableparty/table#59]
What do you think about inviting other DMs to try the tool? Two particular questions:

- Do you think there are any essential features needed before this?
- Do we want to keep registration open to all or require an invitation?

I'd be particularly interested in approaching [Mike Shea](https://slyflourish.com/) as his approach to running games and his [discussion about playing D&D online (Sharing Visuals section)](https://slyflourish.com/running_dnd_online.html) has been in the back of my head for a while.

**Comment by cpytel** [comment]
I am up for it.

I think it would be good to either have a home page, accompanying text, or even do an onboarding call with people that describes what we're going for with Table (specifically what it _doesn't_ do intentionally), and also how to use it.

I would like to improve the way token creation works to the point we're both happy with it, but I also recognize that is a common trap people fall into.

> Do we want to keep registration open to all or require an invitation?

I would default to open, but I don't have a strong opinion.

**Comment by jdbann** [comment]
Closing as we've started inviting people
