### ISSUE TITLE
Sign up not working

### ISSUE THREAD

**Issue by rosy-sanby** [tableparty/table#79]
I cannot sign up.
When I type in name, email and password to sign up, it redirects to table.party/users and clears the password field in the form but nothing else happens.

**Comment by jdbann** [comment]
First of all, I can't thank you enough for being interested in the project and wanting to sign up! We're still in a private beta so new users have to provide a sign up code to register. Currently this code is available to supporters on Patreon.

We're trying to find out how expensive it is to host the tool, and whilst I'm paying for the hosting myself at the moment we want to prioritise access to people who will give regular feedback and help the tool grow.

If you can offer your support then we'd love for you to [join us on Patreon](https://www.patreon.com/tableparty). If you can't financially back the project but would still like to be involved in testing then send an email to help@table.party

**Comment by cpytel** [comment]
I’d also add for completeness that you don’t need an account to play in a campaign, your DM sense you w link to the table when it’s ready.

Thanks!
