### ISSUE TITLE
Multi-select characters

### ISSUE THREAD

**Issue by Macrofig** [tableparty/table#84]
Sometimes, characters move in a direction together, it would be nice to somehow select multiple characters (or even monsters, I suppose) and move them all at once.

**Comment by jdbann** [comment]
Was this also in the same setup as you mentioned in #83, where one person would control all the token movement rather than players controlling their own?

**Comment by Macrofig** [comment]
> Was this also in the same setup as you mentioned in #83, where one person would control all the token movement rather than players controlling their own?

Correct, in our case, one person would control all characters on the map.

**Comment by cpytel** [comment]
In progress in https://github.com/tableparty/table/pull/115

**Comment by cpytel** [comment]
This was done in #115 and is now live. Thanks!
