### ISSUE TITLE
Character movement jitter

### ISSUE THREAD

**Issue by Macrofig** [tableparty/table#85]
When dragging a character around, if the drag happens quickly then, upon drop, there is a jitter with the character icon movement. It seems like the icon movement is updated based on what is sent to the server which makes sense for player screens but not for the DM screen.

Also, moving the map has the same effect - but only when dragging quickly.

![jitter](https://user-images.githubusercontent.com/2633542/83986695-abc88100-a90b-11ea-80f6-985bc810de3a.gif)

**Comment by jdbann** [comment]
Yeah, the token movement is relayed to everyone on that page, including the DM. The movement is blocked whilst the token is being dragged, but when it is released then any further movements are enacted on the token.

With slower, more precise movements then the websocket has usually already sent the move events back to the DM before they have released, but rapid movements like this are likely to get the last few movement events acting on the token.

This will also be true for slower or less reliable connections as events are queued on the socket.

I've been thinking about sending something like a `frame_count` with the move event. So a user dragging a token sends `{ x: 102, y: 221, token_id: "abc", frame_count: 34 }`. If the `frame_count` on the event is greater than the `frame_count` on the token element then the move event is applied to the token.

**Comment by cpytel** [comment]
I've opened https://github.com/tableparty/table/pull/88 to address this.
